title: Mohit Katta
logo: /assets/img/mohit-photo-eclipse.png
description: An Applied Data Analytics Graduate; Researching in NLP; Interested in Healthcare Projects :)
show_downloads: true
theme: jekyll-theme-minimal

# Social media links

social_links:
  linkedin: [https://www.linkedin.com/in/mohit-katta]
