title: Mohit Katta
logo: /assets/img/mohit-photo-eclipse.png
description: Just another Data Science Graduate; Researching in NLP :)
show_downloads: true
theme: jekyll-theme-minimal

# Social media links

social_links:
  linkedin: [https://www.linkedin.com/in/mohit-katta]
